const Dizionario  = [
    {
        e:"an",
        i:"un"
    }, 
    {
        e:"abacus",
        i:"abaco"
    }, 
    {
        e:"abandon", 
        i:"abbandono"
    },
    {
        e:"abandoned",
        i:"abbandonato"
    }, 
    {
        e:"(to) abase", 
        i:"abbandonare"
    }, 
    {
        e:"abasement", 
        i:"umiliazione"
    },
    {
        e:"(to) abash", 
        i:"confondere"
    }, 
    {
        e:"abashment", 
        i:"confusione"
    },
    {
        e:"(to) abate", 
        i:"ridurre"
    },
    {
        e:"abatement", 
        i:"riduzione"
    },
    {
        e:"abattoir", 
        i:"mattatoio"
    },
    {
        e:"abbess", 
        i:"badessa"
    },
    {
        e:"abbey", 
        i:"abbazia"
    },
    {
        e:"abbot", 
        i:"abate"
    },
    {
        e:"abbreviate", 
        i:"abbreviare"
    },
    {
        e:"abbreviation", 
        i:"abbreviazione"
    },
    {
        e:"abdication", 
        i:"abdicazione"
    },
    {
        e:"abdomen", 
        i:"addome"
    },
    {
        e:"abdominal", 
        i:"addominale"
    },
    {
        e:"(to) abduct", 
        i:"rapire"
    },
    {
        e:"abduction", 
        i:"rapimento"
    },
    {
        e:"aberrance", 
        i:"aberrazione"
    },
    {
        e:"aberrant", 
        i:"aberrante"
    },
    {
        e:"aberration", 
        i:"aberrazione"
    },
    {
        e:"(to) abet", 
        i:"favoreggiare"
    },
    {
        e:"abetment", 
        i:"favoreggiamento"
    },
    {
        e:"abetter", 
        i:"favoreggiatore"
    },
    {
        e:"abeyance", 
        i:"sospensione"
    },
    {
        e:"abhor", 
        i:"aborrire"
    },
    {
        e:"abhorrence", 
        i:"ripugnanza"
    },
    {
        e:"abhorrent", 
        i:"ripugnante"
    },
    {
        e:"(to) abide", 
        i:"tollerare"
    },
    {
        e:"abiding", 
        i:"costante"
    },
    {
        e:"ability", 
        i:"abilità"
    },
    {
        e:"abject", 
        i:"abietto"
    },
    {
        e:"abjuration", 
        i:"abiura"
    },
    {
        e:"abjure", 
        i:"abiurare"
    },
    {
        e:"ablaze", 
        i:"in fiamme"
    },
    {
        e:"able", 
        i:"capace"
    },
    {
        e:"ablution", 
        i:"abluzione"
    },
    {
        e:"ably", 
        i:"abilmente"
    },
    {
        e:"abnegate", 
        i:"rinunciare"
    },
    {
        e:"abnegation", 
        i:"abnegazione"
    },
    {
        e:"abnormal", 
        i:"anormale"
    },
    {
        e:"abnormality", 
        i:"anormalità"
    },
    {
        e:"abnormally", 
        i:"eccezionalmente"
    },
    {
        e:"aboard", 
        i:"a bordo"
    },
    {
        e:"abode", 
        i:"residenza"
    },
    {
        e:"(to) abolish", 
        i:"abolire"
    },
    {
        e:"abolition", 
        i:"abolizione"
    },
    {
        e:"abolitionist", 
        i:"abolizionista"
    },
    {
        e:"abominable", 
        i:"abominevole"
    },
    {
        e:"(to) abominate", 
        i:"aberrare"
    },
    {
        e:"abomination", 
        i:"odio"
    },
    {
        e:"aboriginal", 
        i:"aborigeno"
    },
    {
        e:"aborigine", 
        i:"aborigeno"
    },
    {
        e:"(to) abort", 
        i:"interrompere"
    },
    {
        e:"abortion", 
        i:"aborto"
    },
    {
        e:"abortive", 
        i:"abortivo"
    },
    {
        e:"(to) abound", 
        i:"abbondare"
    },
    {
        e:"about", 
        i:"circa"
    },
    {
        e:"above", 
        i:"oltre"
    },
    {
        e:"abrasion", 
        i:"abrasione"
    },
    {
        e:"abrasive", 
        i:"abrasivo"
    },
    {
        e:"(to) abridge", 
        i:"accorciare"
    },
    {
        e:"abridgement", 
        i:"riduzione"
    },
    {
        e:"abroad", 
        i:"all'estero"
    },
    {
        e:"abrogate", 
        i:"abrogare"
    },
    {
        e:"abrogation", 
        i:"abrogazione"
    },
    {
        e:"abrupt", 
        i:"inaspettato"
    },
    {
        e:"abscess", 
        i:"ascesso"
    },
    {
        e:"abscissa", 
        i:"ascissa"
    },
    {
        e:"(to) abscond", 
        i:"fuggire"
    },
    {
        e:"absence", 
        i:"assenza"
    },
    {
        e:"absent", 
        i:"assente"
    },
    {
        e:"absentely", 
        i:"distrattamente"
    },
    {
        e:"absolute", 
        i:"assoluto"
    },
]