const Dizionario  = [
    {
        e:"an",
        i:"un"
    }, 
    {
        e:"abacus",
        i:"abaco"
    }, 
    {
        e:"abandon", 
        i:"abbandono"
    },
    {
        e:"abandoned",
        i:"abbandonato"
    }, 
    {
        e:"(to) abase", 
        i:"abbandonare"
    }, 
    {
        e:"abasement", 
        i:"umiliazione"
    },
    {
        e:"(to) abash", 
        i:"confondere"
    }, 
    {
        e:"abashment", 
        i:"confusione"
    },
    {
        e:"(to) abate", 
        i:"ridurre"
    },
    {
        e:"abatement", 
        i:"riduzione"
    },
    {
        e:"abattoir", 
        i:"mattatoio"
    },
    {
        e:"abbess", 
        i:"badessa"
    },
    {
        e:"abbey", 
        i:"abbazia"
    },
    {
        e:"abbot", 
        i:"abate"
    },
    {
        e:"abbreviate", 
        i:"abbreviare"
    },
    {
        e:"abbreviation", 
        i:"abbreviazione"
    },
    {
        e:"abdication", 
        i:"abdicazione"
    },
    {
        e:"abdomen", 
        i:"addome"
    },
    {
        e:"abdominal", 
        i:"addominale"
    },
    {
        e:"(to) abduct", 
        i:"rapire"
    },
    {
        e:"abduction", 
        i:"rapimento"
    },
    {
        e:"aberrance", 
        i:"aberrazione"
    },
    {
        e:"aberrant", 
        i:"aberrante"
    },
    {
        e:"aberration", 
        i:"aberrazione"
    },
    {
        e:"(to) abet", 
        i:"favoreggiare"
    },
    {
        e:"abetment", 
        i:"favoreggiamento"
    },
    {
        e:"abetter", 
        i:"favoreggiatore"
    },
    {
        e:"abeyance", 
        i:"sospensione"
    },
    {
        e:"abhor", 
        i:"aborrire"
    },
    {
        e:"abhorrence", 
        i:"ripugnanza"
    },
    {
        e:"abhorrent", 
        i:"ripugnante"
    },
    {
        e:"(to) abide", 
        i:"tollerare"
    },
    {
        e:"abiding (agg)", 
        i:"costante"
    },
    {
        e:"ability", 
        i:"abilità"
    },
    {
        e:"abject", 
        i:"abietto"
    },
    {
        e:"abjuration", 
        i:"abiura"
    },
    {
        e:"abjure", 
        i:"abiurare"
    },
    {
        e:"ablaze", 
        i:"in fiamme"
    },
    {
        e:"able", 
        i:"capace"
    },
    {
        e:"ablution", 
        i:"abluzione"
    },
    {
        e:"ably", 
        i:"abilmente"
    },
    {
        e:"abnegate", 
        i:"rinunciare"
    },
    {
        e:"abnegation", 
        i:"abnegazione"
    },
    {
        e:"abnormal", 
        i:"anormale"
    },
    {
        e:"abnormality", 
        i:"anormalità"
    },
    {
        e:"abnormally", 
        i:"eccezionalmente"
    },
    {
        e:"aboard", 
        i:"a bordo"
    },
    {
        e:"abode", 
        i:"residenza"
    },
    {
        e:"(to) abolish", 
        i:"abolire"
    },
    {
        e:"abolition", 
        i:"abolizione"
    },
    {
        e:"abolitionist", 
        i:"abolizionista"
    },
    {
        e:"abominable", 
        i:"abominevole"
    },
    {
        e:"(to) abominate", 
        i:"aberrare"
    },
    {
        e:"abomination", 
        i:"odio"
    },
    {
        e:"aboriginal", 
        i:"aborigeno"
    },
    {
        e:"aborigine", 
        i:"aborigeno"
    },
    {
        e:"(to) abort", 
        i:"interrompere"
    },
    {
        e:"abortion", 
        i:"aborto"
    },
    {
        e:"abortive", 
        i:"abortivo"
    },
    {
        e:"(to) abound", 
        i:"abbondare"
    },
    {
        e:"about", 
        i:"circa"
    },
    {
        e:"above", 
        i:"oltre"
    },
    {
        e:"abrasion", 
        i:"abrasione"
    },
    {
        e:"abrasive", 
        i:"abrasivo"
    },
    {
        e:"(to) abridge", 
        i:"accorciare"
    },
    {
        e:"abridgement", 
        i:"riduzione"
    },
    {
        e:"abroad", 
        i:"all'estero"
    },
    {
        e:"abrogate", 
        i:"abrogare"
    },
    {
        e:"abrogation", 
        i:"abrogazione"
    },
    {
        e:"abrupt", 
        i:"inaspettato"
    },
    {
        e:"abscess", 
        i:"ascesso"
    },
    {
        e:"abscissa", 
        i:"ascissa"
    },
    {
        e:"(to) abscond", 
        i:"fuggire"
    },
    {
        e:"absence", 
        i:"assenza"
    },
    {
        e:"absent", 
        i:"assente"
    },
    {
        e:"absentely", 
        i:"distrattamente"
    },
    {
        e:"absolute", 
        i:"assoluto"
    },
    {
        e:"absolutness", 
        i:"assolutezza"
    },
    {
        e:"absolution", 
        i:"assoluzione"
    },
    {
        e:"absolutism", 
        i:"assolutismo"
    },
    {
        e:"absolutist", 
        i:"assolutista"
    },
    {
        e:"(to) absolve", 
        i:"assolvere"
    },
    {
        e:"(to) absorb", 
        i:"assorbire"
    },
    {
        e:"absorbed", 
        i:"assorbito"
    },
    {
        e:"absorbent", 
        i:"assorbente"
    },
    {
        e:"absorbing (agg)", 
        i:"avvincente"
    },
    {
        e:"absorption", 
        i:"assorbimento"
    },
    {
        e:"(to) abstain", 
        i:"astenersi"
    },
    {
        e:"abstainer", 
        i:"astenuto"
    },
    {
        e:"abstemious", 
        i:"sobrio"
    },
    {
        e:"abstemiousness", 
        i:"sobrietà"
    },
    {
        e:"abstention", 
        i:"astensione"
    },
    {
        e:"abstinence", 
        i:"astinenza"
    },
    {
        e:"abstinent", 
        i:"astinente"
    },
    {
        e:"abstract", 
        i:"astratto"
    },
    {
        e:"(to) abstract", 
        i:"sottrarre"
    },
    {
        e:"abstracted", 
        i:"distratto"
    },
    {
        e:"abstraction", 
        i:"astrazione"
    },
    {
        e:"abstractionism", 
        i:"astrattismo"
    },
    {
        e:"abstractionist", 
        i:"astrattista"
    },
    {
        e:"abstruse", 
        i:"astruso"
    },
    {
        e:"absurd", 
        i:"assurdo"
    },
    {
        e:"absurdity", 
        i:"assurdità"
    },
    {
        e:"abulia", 
        i:"abulia"
    },
    {
        e:"abundance", 
        i:"abbondanza"
    },
    {
        e:"abundant", 
        i:"abbondante"
    },
    {
        e:"(to) abuse", 
        i:"approfittare"
    },
    {
        e:"abusive", 
        i:"abusivo"
    },
    {
        e:"(to) about (to something)", 
        i:"confinare"
    },
    {
        e:"abutment", 
        i:"appoggio"
    },
    {
        e:"abysmal", 
        i:"terribile"
    },
    {
        e:"abyss", 
        i:"abisso"
    },
    {
        e:"abyssinian", 
        i:"abissino"
    },
    {
        e:"acacia", 
        i:"acacia"
    },
    {
        e:"academic", 
        i:"accademico"
    },
    {
        e:"academician (person)", 
        i:"accademico"
    },
    {
        e:"academy", 
        i:"accademia"
    },
    {
        e:"acanthus", 
        i:"acanto"
    },
    {
        e:"(to) accede", 
        i:"accedere"
    },
    {
        e:"(to) accelerate", 
        i:"accelerare"
    },
    {
        e:"acceleration", 
        i:"accelerazione"
    },
    {
        e:"accelerator", 
        i:"acceleratore"
    },
    {
        e:"accent", 
        i:"accento"
    },
    {
        e:"(to) accent", 
        i:"accentare"
    },
    {
        e:"(to) accentuate", 
        i:"accentuare"
    },
    {
        e:"accentuation", 
        i:"accentuazione"
    },
    {
        e:"(to) accept", 
        i:"accettare"
    },
    {
        e:"acceptable", 
        i:"accettabile"
    },
    {
        e:"acceptance", 
        i:"accettazione"
    },
    {
        e:"accepter", 
        i:"accettante"
    },
    {
        e:"acceptor", 
        i:"accettante"
    },
    {
        e:"access", 
        i:"accesso"
    },
    {
        e:"(to) access", 
        i:"accedere"
    },
    {
        e:"accessary", 
        i:"complice"
    },
    {
        e:"accessible", 
        i:"accessibile"
    },
    {
        e:"accession", 
        i:"ascesa"
    },
    {
        e:"accessorial (agg)", 
        i:"accessorio"
    },
    {
        e:"accessory", 
        i:"accessorio"
    },
    {
        e:"access road", 
        i:"strada secondaria"
    },
    {
        e:"accidence", 
        i:"morfologia"
    },
    {
        e:"accident", 
        i:"incidente"
    },
    {
        e:"accidental", 
        i:"accidentale"
    },
    {
        e:"acclaim", 
        i:"consenso"
    },
    {
        e:"(to) acclaim", 
        i:"acclamare"
    },
    {
        e:"acclamation", 
        i:"acclamazione"
    },
    {
        e:"acclimate", 
        i:"acclimatizzarsi"
    },
    {
        e:"acclimatization", 
        i:"acclimatizzarsi"
    },
    {
        e:"(to) acclimatize", 
        i:"acclimatizzarsi"
    },  
    {
        e:"accolade", 
        i:"lode"
    },   
    {
        e:"(to) accomodate", 
        i:"accomodare"
    },
    {
        e:"accomodating (agg)", 
        i:"servizievole"
    },
    {
        e:"accomodation", 
        i:"alloggio"
    },
    {
        e:"accompaniment", 
        i:"accompagnamento"
    },
    {
        e:"accompanist", 
        i:"accompagnatore"
    },
    {
        e:"(to) accompany", 
        i:"accompagnare"
    },
    {
        e:"accomplice", 
        i:"complice"
    },
    {
        e:"(to) accomplish", 
        i:"compiere"
    },
    {
        e:"accomplished", 
        i:"finito"
    },
    {
        e:"accomplishment", 
        i:"compimento"
    },
    {
        e:"accord", 
        i:"accordo"
    },
    {
        e:"(to) accord", 
        i:"accordare"
    },
    {
        e:"accordance", 
        i:"accordo"
    },
    {
        e:"accordingly", 
        i:"quindi"
    },
    {
        e:"according to", 
        i:"secondo"
    },
    {
        e:"accordion", 
        i:"fisarmonica"
    },
    {
        e:"(to) acost", 
        i:"avvicinare"
    },
    {
        e:"account", 
        i:"conto"
    },
    {
        e:"(to) account", 
        i:"stimare"
    },
    {
        e:"accountable", 
        i:"responsabile"
    },
    {
        e:"accountancy", 
        i:"contabilità"
    },
    {
        e:"accountant", 
        i:"contabile"
    },
    {
        e:"accounting", 
        i:"contabilita"
    },
    {
        e:"(to) accredit", 
        i:"accreditare"
    },
    {
        e:"accretion", 
        i:"accrescimento"
    },
    {
        e:"(to) acrue", 
        i:"maturare"
    },
    {
        e:"(to) accumulate", 
        i:"accumulare"
    },
    {
        e:"accumuluation", 
        i:"accumulazione"
    },
    {
        e:"accumulative", 
        i:"accumulativo"
    },
    {
        e:"accumulator", 
        i:"accumulatore"
    },
    {
        e:"accuracy", 
        i:"precisione"
    },
    {
        e:"accurate", 
        i:"preciso"
    },
    {
        e:"accursed", 
        i:"maledetto"
    },
    {
        e:"accusable", 
        i:"accusabile"
    },
    {
        e:"accusation", 
        i:"accusa"
    },
    {
        e:"(to) accuse", 
        i:"accusare"
    },
    {
        e:"accused", 
        i:"accusato"
    },
    {
        e:"accuser", 
        i:"accusatore"
    },
    {
        e:"(to) accustom", 
        i:"abituare"
    },  
    {
        e:"accustomed", 
        i:"abituato"
    },
    {
        e:"ace", 
        i:"asso"
    },
    {
        e:"acerbity", 
        i:"acerbità"
    },
    {
        e:"acetate", 
        i:"acetato"
    },
    {
        e:"acetic", 
        i:"acetico"
    },
    {
        e:"(to) acetify", 
        i:"acetificare"
    },
    {
        e:"acetone", 
        i:"acetone"
    },
    {
        e:"acetylene", 
        i:"acetilene"
    },
    {
        e:"ache", 
        i:"dolore"
    },
    {
        e:"(to) ache", 
        i:"dolere"
    },
    {
        e:"(to) achieve", 
        i:"ottenere"
    },
    {
        e:"achievement", 
        i:"obiettivo"
    },
    {
        e:"achromatic", 
        i:"acromatico"
    },
    {
        e:"acid", 
        i:"acido"
    },
    {
        e:"(to) acidify", 
        i:"acidificare"
    },
    {
        e:"acidity", 
        i:"acidità"
    },
    {
        e:"(to) acknowledge", 
        i:"riconoscere"
    },  
    {
        e:"acknowledgement", 
        i:"riconoscimento"
    },
    {
        e:"acme", 
        i:"acme"
    },
    {
        e:"acne", 
        i:"acne"
    },
    {
        e:"acolyte", 
        i:"accolito"
    },
    {
        e:"acorn", 
        i:"ghianda"
    },
    {
        e:"acoustic", 
        i:"acustico"
    },
    {
        e:"acoustics", 
        i:"acustica"
    },
    {
        e:"(to) acquaint", 
        i:"informare"
    },
    {
        e:"acquaintance", 
        i:"conoscenza"
    },
    {
        e:"(to) acquiesce", 
        i:"acconsentire"
    },
    {
        e:"acquiescence", 
        i:"arrendevolezza"
    },
    {
        e:"acquiescent", 
        i:"arrendevole"
    },
    {
        e:"(to) acquire", 
        i:"acquisire"
    },
    {
        e:"acquisition", 
        i:"acquisizione"
    },
    {
        e:"acquisitive", 
        i:"avido"
    },
    {
        e:"(to) acquit", 
        i:"assolvere"
    },
    {
        e:"acquittal", 
        i:"assoluzione"
    },
    {
        e:"acre", 
        i:"acro"
    },
    {
        e:"acrid", 
        i:"aspro"
    },
    {
        e:"acrimonious", 
        i:"astioso"
    },
    {
        e:"acrimony", 
        i:"astiosità"
    },
    {
        e:"acrobat", 
        i:"acrobata"
    },
    {
        e:"acrobatic", 
        i:"acrobatico"
    },
    {
        e:"acrobatics", 
        i:"acrobazia"
    },
    {
        e:"acronym", 
        i:"acronimo"
    },
    {
        e:"across", 
        i:"attraverso"
    },
    {
        e:"acrostic", 
        i:"acrostico"
    },
    {
        e:"acrylic", 
        i:"acrilico"
    },
    {
        e:"act", 
        i:"azione"
    },
    {
        e:"(to) act", 
        i:"agire"
    },
    {
        e:"acting", 
        i:"recitazione"
    },
    {
        e:"action", 
        i:"azione"
    },
    {
        e:"actionable", 
        i:"azionabile"
    },
    {
        e:"(to) activate", 
        i:"attivare"
    },
    {
        e:"active", 
        i:"attivo"
    },
    {
        e:"activist", 
        i:"attivista"
    },
    {
        e:"activity", 
        i:"attività"
    },
    {
        e:"actor", 
        i:"attore"
    },
    {
        e:"actress", 
        i:"attrice"
    },
    {
        e:"actual", 
        i:"attuale"
    },
    {
        e:"actually", 
        i:"veramente"
    },
    {
        e:"actuary", 
        i:"attuario"
    },
    {
        e:"(to) actuate", 
        i:"attuare"
    },
    {
        e:"acuity", 
        i:"acutezza"
    },
    {
        e:"acumen", 
        i:"acume"
    },
    {
        e:"acupuncture", 
        i:"agopuntura"
    },
    {
        e:"acupuncturist", 
        i:"agopunturista"
    },
    {
        e:"acute", 
        i:"acuto"
    },
    {
        e:"ad", 
        i:"pubblicità"
    },
    {
        e:"adage", 
        i:"adagio"
    },
    {
        e:"adam", 
        i:"adamo"
    },
    {
        e:"adamant", 
        i:"risoluto"
    },
    {
        e:"(to) adapt", 
        i:"adattare"
    },
    {
        e:"adaptibility", 
        i:"adattabilità"
    },
    {
        e:"adaptable", 
        i:"adattabile"
    },
    {
        e:"adaptation", 
        i:"adattamento"
    },
    {
        e:"adapter", 
        i:"adattatore"
    },
    {
        e:"(to) add", 
        i:"aggiungere"
    },
    {
        e:"addendum", 
        i:"addendo"
    },
    {
        e:"adder", 
        i:"vipera"
    },
    {
        e:"addicted", 
        i:"dipendente"
    },
    {
        e:"addiction", 
        i:"dipendenza"
    },
    {
        e:"addictive", 
        i:"provoca dipendenza"
    },
    {
        e:"addition", 
        i:"addizione"
    },
    {
        e:"additional", 
        i:"supplementare"
    },
    {
        e:"additionally", 
        i:"inoltre"
    },
    {
        e:"additive", 
        i:"additivo"
    },
    {
        e:"(to) addle", 
        i:"confondere"
    },
    {
        e:"addled", 
        i:"marcio"
    },
    {
        e:"address", 
        i:"indirizzo"
    },
    {
        e:"(to) address", 
        i:"indirizzare"
    },
    {
        e:"addressee", 
        i:"destinatario"
    },
    {
        e:"(to) aduce", 
        i:"addurre"
    },
    {
        e:"adenoids", 
        i:"adenoidi"
    },
    {
        e:"adenoma", 
        i:"adenoma"
    },
    {
        e:"adept", 
        i:"esperto"
    },
    {
        e:"adequacy", 
        i:"adeguatezza"
    },
    {
        e:"adequate", 
        i:"adeguato"
    },
    {
        e:"(to) adhere", 
        i:"aderire"
    },
    {
        e:"adherence", 
        i:"aderenza"
    },
    {
        e:"adherent", 
        i:"aderente"
    },
    {
        e:"adhesion", 
        i:"adesione"
    },
    {
        e:"adhesive", 
        i:"adesivo"
    },
    {
        e:"adipose", 
        i:"adiposo"
    },
    {
        e:"adjacent", 
        i:"adiacente"
    },
    {
        e:"adjective", 
        i:"aggettivo"
    },
    {
        e:"(to) adjoin", 
        i:"confinare"
    },
    {
        e:"adjoining", 
        i:"adiacente"
    },
    {
        e:"(to) adjourn", 
        i:"aggiornare"
    },
    {
        e:"adjournment", 
        i:"aggiornamento"
    },
    {
        e:"(to) adjudge", 
        i:"giudicare"
    },
    {
        e:"(to) adjudicate", 
        i:"aggiudicare"
    },
    {
        e:"adjudicator", 
        i:"arbitro"
    },
    {
        e:"adjunct", 
        i:"accessorio"
    },
    {
        e:"(to) adjust", 
        i:"aggiustare"
    },
    {
        e:"adjustable", 
        i:"aggiustabile"
    },
    {
        e:"adjustment", 
        i:"aggiustamento"
    },
    {
        e:"adjutant", 
        i:"aiutante"
    },
    {
        e:"(to) ad-lib", 
        i:"improvvisare"
    },
    {
        e:"adman", 
        i:"pubblicitario"
    },
    {
        e:"admin", 
        i:"amministratore"
    },
    {
        e:"(to) administer", 
        i:"amministrare"
    },
    {
        e:"administration", 
        i:"amministrazione"
    },
    {
        e:"administrative", 
        i:"amministrativo"
    },
    {
        e:"administrator", 
        i:"amministratore"
    },
    {
        e:"admirable", 
        i:"ammirabile"
    },
    {
        e:"admiral", 
        i:"ammiraglio"
    },
    {
        e:"admiration", 
        i:"ammirazione"
    },
    {
        e:"(to) admire", 
        i:"ammirare"
    },
    {
        e:"admirer", 
        i:"ammiratore"
    },
    {
        e:"admiring (agg)", 
        i:"ammirato"
    },
    {
        e:"admissible", 
        i:"ammissibile"
    },
    {
        e:"admission", 
        i:"ammissione"
    },
    {
        e:"(to) admit", 
        i:"ammettere"
    },
    {
        e:"admittedly", 
        i:"dichiaratamente"
    },
    {
        e:"admixture", 
        i:"additivo"
    },
    {
        e:"(to) admonish", 
        i:"ammonire"
    },
    {
        e:"admonition", 
        i:"ammonizione"
    },
    {
        e:"ado", 
        i:"confusione"
    },
    {
        e:"adolescence", 
        i:"adolescenza"
    },
    {
        e:"adolescent", 
        i:"adolescente"
    },
    {
        e:"(to) adopt", 
        i:"adottare"
    },
    {
        e:"adoption", 
        i:"adozione"
    },
    {
        e:"adoptive", 
        i:"adottivo"
    },
    {
        e:"adorable", 
        i:"adorabile"
    },
    {
        e:"adoration", 
        i:"adorazione"
    },
    {
        e:"(to) adore", 
        i:"adorare"
    },
    {
        e:"(to) adorn", 
        i:"adornare"
    },
    {
        e:"adornment", 
        i:"ornamento"
    },
    {
        e:"adrenaline", 
        i:"adrenalina"
    },
    {
        e:"adriatic", 
        i:"adriatico"
    },
    {
        e:"adrift", 
        i:"deriva"
    },
    {
        e:"adulation", 
        i:"adulazione"
    },
    {
        e:"adult", 
        i:"adulto"
    },
    {
        e:"(to) adulterate", 
        i:"adulterare"
    },
    {
        e:"adulteration", 
        i:"adulterazione"
    },
    {
        e:"adulterer", 
        i:"adultero"
    },
    {
        e:"adulteress", 
        i:"adultera"
    },
    {
        e:"adulterous", 
        i:"adultero"
    },
    {
        e:"adultery", 
        i:"adulterio"
    },
    {
        e:"adulthood", 
        i:"età adulta"
    },
    {
        e:"adumbrate", 
        i:"adombrare"
    },
    {
        e:"advance", 
        i:"avanzamento"
    },
    {
        e:"(to) advance", 
        i:"avanzare"
    },
    {
        e:"advanced", 
        i:"avanzato"
    },
    {
        e:"advancement", 
        i:"avanzamento"
    },
    {
        e:"advantage", 
        i:"vantaggio"
    },
    {
        e:"(to) advantage", 
        i:"avvantaggiare"
    },
    {
        e:"advantageous", 
        i:"vantaggioso"
    },
    {
        e:"advent", 
        i:"avvento"
    },
    {
        e:"adventitous", 
        i:"casuale"
    },
    {
        e:"adventure", 
        i:"avventura"
    },
    {
        e:"adventurer", 
        i:"avventuriero"
    },
    {
        e:"adventuress", 
        i:"avventuriera"
    },
    {
        e:"adventurous", 
        i:"avventuroso"
    },
    {
        e:"adverb", 
        i:"avverbio"
    },
    {
        e:"adverbial", 
        i:"avverbiale"
    },
    {
        e:"asversarial", 
        i:"rivale"
    },
    {
        e:"adversary", 
        i:"avversario"
    },
    {
        e:"adverse", 
        i:"contrario"
    },
    {
        e:"adversely", 
        i:"negativamente"
    },
    {
        e:"adversity", 
        i:"avversità"
    },
    {
        e:"advert", 
        i:"pubblicità"
    },
    {
        e:"(to) advertize", 
        i:"pubblicizzare"
    },
    {
        e:"advertisement", 
        i:"pubblicità"
    },
    {
        e:"advertiser", 
        i:"inserzionista"
    },
    {
        e:"advertising (agg)", 
        i:"pubblicità"
    },
    {
        e:"advice", 
        i:"consiglio"
    },
    {
        e:"advisability", 
        i:"opportunità"
    },
    {
        e:"advisable", 
        i:"consigliabile"
    },
    {
        e:"(to) advise", 
        i:"consigliare"
    },
    {
        e:"advisedly", 
        i:"volutamente"
    },
    {
        e:"adviser", 
        i:"consigliere"
    },
    {
        e:"advocacy", 
        i:"difesa"
    },
    {
        e:"advocate", 
        i:"difensore"
    },
    {
        e:"(to) advocate", 
        i:"difendere"
    },
    {
        e:"aeon", 
        i:"eternità"
    },
    {
        e:"(to) aerate", 
        i:"aerare"
    },
    {
        e:"aeration", 
        i:"aerazione"
    },
    {
        e:"aerial", 
        i:"aereo"
    },
    {
        e:"aeriform", 
        i:"aeriforme"
    },
    {
        e:"aerobatics", 
        i:"acrobatica aerea"
    },
    {
        e:"aerobics", 
        i:"aerobica"
    },
    {
        e:"aerodynamic", 
        i:"aerodinamico"
    },
    {
        e:"aerodynamics", 
        i:"aerodinamica"
    },
    {
        e:"aerofoil", 
        i:"alettone"
    },
    {
        e:"aerograph", 
        i:"aerografo"
    },
    {
        e:"aerometer", 
        i:"aerometro"
    },
    {
        e:"aeronautical", 
        i:"aeronautico"
    },
    {
        e:"aeronautics", 
        i:"aeronautica"
    },
    {
        e:"aerophone", 
        i:"aerofono"
    },
    {
        e:"aeroplane", 
        i:"aeroplano"
    },
    {
        e:"aerosol", 
        i:"aerosol"
    },
    {
        e:"aerospace", 
        i:"aerospaziale"
    },
    {
        e:"aesthete", 
        i:"esteta"
    },
    {
        e:"aesthetic", 
        i:"estetico"
    },
    {
        e:"aestheticism", 
        i:"estetismo"
    },
    {
        e:"afar", 
        i:"lontano"
    },
    {
        e:"affability", 
        i:"cortesia"
    },
    {
        e:"affable", 
        i:"cortese"
    },
    {
        e:"affair", 
        i:"affare"
    },
    {
        e:"(to) affect", 
        i:"influenzare"
    },
    {
        e:"affectiation", 
        i:"affettazione"
    },
    {
        e:"affected", 
        i:"affettato"
    },
    {
        e:"affection", 
        i:"affetto"
    },
    {
        e:"affectionate", 
        i:"affettuoso"
    },
    {
        e:"affiliate", 
        i:"affiliato"
    },
    {
        e:"affiliation", 
        i:"affiliazione"
    },
    {
        e:"affinity", 
        i:"affinità"
    },
    {
        e:"(to) affirm", 
        i:"affermare"
    },
    {
        e:"affirmation", 
        i:"affermazione"
    },
    {
        e:"affirmative", 
        i:"affermativo"
    },
    {
        e:"affix", 
        i:"affisso"
    },
    {
        e:"(to) affix", 
        i:"affiggere"
    },
    {
        e:"(to) afflict", 
        i:"affliggere"
    },
    {
        e:"affliction", 
        i:"afflizione"
    },
    {
        e:"affluence", 
        i:"ricchezza"
    },
    {
        e:"affluent", 
        i:"ricco"
    },
    {
        e:"afflux", 
        i:"afflusso"
    },
    {
        e:"(to) afford", 
        i:"permettere"
    },
    {
        e:"(to) afforest", 
        i:"imboschire"
    },
    {
        e:"afforestation", 
        i:"imboschimento"
    },
    {
        e:"affray", 
        i:"rissa"
    },
    {
        e:"affront", 
        i:"affronto"
    },
    {
        e:"(to) affront", 
        i:"insultare"
    },
    {
        e:"afire", 
        i:"in fiamme"
    },
    {
        e:"aflame", 
        i:"in fiamme"
    },
    {
        e:"afloat", 
        i:"a galla"
    },
    {
        e:"afoot", 
        i:"in corso"
    },
    {
        e:"afraid", 
        i:"spaventato"
    },
    {
        e:"afresh", 
        i:"da capo"
    },
    {
        e:"aft", 
        i:"a poppa"
    },
    {
        e:"after", 
        i:"dopo"
    },
    {
        e:"afterglow", 
        i:"tramonto"
    },
    {
        e:"afterlife", 
        i:"aldilà"
    },
    {
        e:"afternoon", 
        i:"pomeriggio"
    },
    {
        e:"afters", 
        i:"dessert"
    },
    {
        e:"aftershave", 
        i:"dopobarba"
    },
    {
        e:"aftertaste", 
        i:"retrogusto"
    },
    {
        e:"afterthought", 
        i:"ripensamento"
    },
    {
        e:"afterward", 
        i:"poi"
    },
    {
        e:"again", 
        i:"di nuovo"
    },
    {
        e:"against", 
        i:"contro"
    },
    {
        e:"agape", 
        i:"stupito"
    },
    {
        e:"agate", 
        i:"agata"
    },
    {
        e:"age", 
        i:"età"
    },
    {
        e:"(to) age", 
        i:"invecchiare"
    },
    {
        e:"aged", 
        i:"vecchio"
    },
    {
        e:"ageing", 
        i:"invecchiamento"
    },
    {
        e:"ageless", 
        i:"senza tempo"
    },
    {
        e:"agency", 
        i:"agenzia"
    },
    {
        e:"agenda", 
        i:"agenda"
    },
    {
        e:"agent", 
        i:"agente"
    },
    {
        e:"(to) agglomerate", 
        i:"agglomerare"
    },
    {
        e:"agglomeration", 
        i:"agglomerazione"
    },
    {
        e:"(to) agglutinate", 
        i:"agglutinare"
    },
    {
        e:"(to) aggrandize", 
        i:"ingrandire"
    },
    {
        e:"(to) aggravate", 
        i:"aggavare"
    },
    {
        e:"aggravating", 
        i:"irritante"
    },
    {
        e:"aggregate", 
        i:"totale"
    },
    {
        e:"(to) aggregate", 
        i:"aggregare"
    },
    {
        e:"aggression", 
        i:"aggressione"
    },
    {
        e:"aggressive", 
        i:"aggressivo"
    },
    {
        e:"aggressiveness", 
        i:"agressività"
    },
    {
        e:"aggressor", 
        i:"aggressore"
    },
    {
        e:"aggrieved", 
        i:"dispiaciuto"
    },
    {
        e:"aggro", 
        i:"aggressività"
    },
    {
        e:"aghast", 
        i:"spaventato"
    },
    {
        e:"agile", 
        i:"agile"
    },
    {
        e:"agility", 
        i:"agilità"
    },
    {
        e:"aging", 
        i:"invecchiamento"
    },
    {
        e:"ageing", 
        i:"invecchiamento"
    },
    {
        e:"agio", 
        i:"aggio"
    },
    {
        e:"(to) agitate", 
        i:"agitare"
    },
    {
        e:"agitation", 
        i:"agitazione"
    },
    {
        e:"agitator", 
        i:"agitatore"
    },
    {
        e:"agnostic", 
        i:"agnostico"
    },
    {
        e:"agnosticism", 
        i:"agnosticismo"
    },
    {
        e:"ago", 
        i:"fa"
    },
    {
        e:"agonistic", 
        i:"agonistico"
    },
    {
        e:"(to) agonize", 
        i:"agonizzare"
    },
    {
        e:"agonizing (agg)", 
        i:"angoscioso"
    },
    {
        e:"agony", 
        i:"agonia"
    },
    {
        e:"agopraphobia", 
        i:"agorafobia"
    },
    {
        e:"agraffe", 
        i:"graffa"
    },
    {
        e:"agrarian", 
        i:"agrario"
    },
    {
        e:"(to) agree", 
        i:"accordare"
    },
    {
        e:"agreed", 
        i:"accordato"
    },
    {
        e:"agremeent", 
        i:"accordo"
    },
    {
        e:"agricultural", 
        i:"agricolo"
    },
    {
        e:"agriculture", 
        i:"agricoltura"
    },
    {
        e:"agronomics", 
        i:"agronomia"
    },
    {
        e:"agronomist", 
        i:"agronomo"
    },
    {
        e:"aground", 
        i:"in secca"
    },
    {
        e:"ahead", 
        i:"avanti"
    },
    {
        e:"aid", 
        i:"soccorso"
    },
    {
        e:"(to) aid", 
        i:"soccorrere"
    },
    {
        e:"aide", 
        i:"assistente"
    },
    {
        e:"(to) ail", 
        i:"soffrire"
    },
    {
        e:"aim", 
        i:"mira"
    },
    {
        e:"(to) aim", 
        i:"mirare"
    },
    {
        e:"aimless", 
        i:"senza scopo"
    },
    {
        e:"air", 
        i:"aria"
    },
    {
        e:"airbag", 
        i:"airbag"
    },
    {
        e:"airbase", 
        i:"base aerea"
    },
    {
        e:"airborne", 
        i:"aviotrasporto"
    },
    {
        e:"airbrick", 
        i:"mattone forato"
    },
    {
        e:"airbus", 
        i:"aerobus"
    },
    {
        e:"airdrop", 
        i:"lancio"
    },
    {
        e:"airforce", 
        i:"aeronautica militare"
    },
    {
        e:"airgun", 
        i:"fucile ad aria compressa"
    },
    {
        e:"airline", 
        i:"compagnia aerea"
    },
    {
        e:"airlift", 
        i:"ponte aereo"
    },
    {
        e:"airman", 
        i:"aviere"
    },
    {
        e:"airplane", 
        i:"aeroplano"
    },
    {
        e:"airport", 
        i:"aeroporto"
    },
    {
        e:"airship", 
        i:"aronave"
    },
    {
        e:"airspace", 
        i:"spazio aereo"
    },
    {
        e:"air-strike", 
        i:"attacco aereo"
    },
    {
        e:"airy", 
        i:"areoso"
    },
    {
        e:"aisle", 
        i:"corridoio"
    },
    {
        e:"alabaster", 
        i:"alabastro"
    },
    {
        e:"alarm", 
        i:"allarme"
    },
    {
        e:"alarm clock", 
        i:"sveglia"
    },
    {
        e:"alarming (agg)", 
        i:"allarmante"
    },
    {
        e:"alarmist", 
        i:"allarmista"
    },
    {
        e:"albatross", 
        i:"albatross"
    },
    {
        e:"albino", 
        i:"albino"
    },
    {
        e:"album", 
        i:"album"
    },
    {
        e:"albumin", 
        i:"albumina"
    },
    {
        e:"alchemist", 
        i:"alchimista"
    },
    {
        e:"alchemy", 
        i:"alchimia"
    },
    {
        e:"alcohol", 
        i:"alcol"
    },
    {
        e:"alcoholic", 
        i:"alcolico"
    },
    {
        e:"alcoholism", 
        i:"alcolismo"
    },
    {
        e:"alcove", 
        i:"nicchia"
    },
    {
        e:"aldehyde", 
        i:"aldeide"
    },
    {
        e:"alder", 
        i:"ontano"
    },
    {
        e:"ale", 
        i:"birra"
    },
    {
        e:"alert", 
        i:"allarme"
    },
    {
        e:"algebra", 
        i:"algebra"
    },
    {
        e:"algebraical", 
        i:"algebrico"
    },
    {
        e:"algorithm", 
        i:"algoritmo"
    },
    {
        e:"alias", 
        i:"pseudonimo"
    },
    {
        e:"alien", 
        i:"alieno"
    },
    {
        e:"(to) alienate", 
        i:"alienare"
    },
    {
        e:"alienation", 
        i:"alienazione"
    },
    {
        e:"alight", 
        i:"acceso"
    },
    {
        e:"(to) alight", 
        i:"scendere"
    },
    {
        e:"(to) align", 
        i:"allineare"
    },
    {
        e:"alignment", 
        i:"allineamento"
    },
    {
        e:"alike", 
        i:"simile"
    },
    {
        e:"alimentary", 
        i:"alimentare"
    },
    {
        e:"alive", 
        i:"vivo"
    },
    {
        e:"alkaline", 
        i:"alcalino"
    },
    {
        e:"alkaloid", 
        i:"alcaloide"
    },
    {
        e:"all", 
        i:"tutto"
    },
    {
        e:"allegiance", 
        i:"fedeltà"
    },
    {
        e:"allegorical", 
        i:"allegorico"
    },
    {
        e:"allegory", 
        i:"allegoria"
    },
    {
        e:"allergen", 
        i:"allergene"
    },
    {
        e:"allergenic", 
        i:"allergenico"
    },
    {
        e:"allergic", 
        i:"allergico"
    },
    {
        e:"allergist", 
        i:"allergolog"
    },
    {
        e:"allergy", 
        i:"allergia"
    },
    {
        e:"(to) alleviate", 
        i:"alleviare"
    },
    {
        e:"alleviation", 
        i:"alleviazione"
    },
    {
        e:"alley", 
        i:"vialetto"
    },
    {
        e:"all fours", 
        i:"gattoni"
    },
    {
        e:"alliance", 
        i:"alleanza"
    },
    {
        e:"allied", 
        i:"alleato"
    },
    {
        e:"alligator", 
        i:"alligatore"
    },
    {
        e:"all-in", 
        i:"tutto incluso"
    },
    {
        e:"alliteration", 
        i:"allitterazione"
    },
    {
        e:"(to) allocate", 
        i:"assegnare"
    },
    {
        e:"allocation", 
        i:"assegnazione"
    },
    {
        e:"allocution", 
        i:"allocuzione"
    },
    {
        e:"(to) allot", 
        i:"distribuire"
    },
    {
        e:"allotment", 
        i:"lotto"
    },
    {
        e:"allotrope", 
        i:"allotropo"
    },
    {
        e:"(to) allow", 
        i:"permettere"
    },
    {
        e:"allowable", 
        i:"ammissibile"
    },
    {
        e:"allowance", 
        i:"indennità"
    },
    {
        e:"alloy", 
        i:"lega"
    },
    {
        e:"(to) alloy", 
        i:"legare"
    },
    {
        e:"all right", 
        i:"a posto"
    },
    {
        e:"all round", 
        i:"in generale"
    },
    {
        e:"(to) allude", 
        i:"alludere"
    },
    {
        e:"allure", 
        i:"fascino"
    },
    {
        e:"(to) allure", 
        i:"affascinare"
    },
    {
        e:"alluring (agg)", 
        i:"affascinante"
    },
    {
        e:"allusion", 
        i:"allusione"
    },
    {
        e:"allusive", 
        i:"allusivo"
    },
    {
        e:"alluvial", 
        i:"alluvionale"
    },
    {
        e:"ally", 
        i:"alleato"
    },
    {
        e:"(to) ally", 
        i:"alleare"
    },
    {
        e:"almanac", 
        i:"almanacco"
    },
    {
        e:"almighty", 
        i:"grande"
    },
    {
        e:"almond", 
        i:"mandorla"
    },
    {
        e:"almost", 
        i:"quasi"
    },
    {
        e:"alms", 
        i:"elemosina"
    },
    {
        e:"aloft", 
        i:"in aria"
    },
    {
        e:"alone", 
        i:"solo"
    },
    {
        e:"along", 
        i:"avanti"
    },
    {
        e:"alongside", 
        i:"a fianco"
    },
    {
        e:"aloof", 
        i:"in disparte"
    },
    {
        e:"aloud", 
        i:"rumoroso"
    },
    {
        e:"alp", 
        i:"alpe"
    },
    {
        e:"alpaca", 
        i:"alpaca"
    },
    {
        e:"alpha", 
        i:"alfa"
    },
    {
        e:"alphabet", 
        i:"alfabeto"
    },
    {
        e:"alphabetical", 
        i:"alfabetico"
    },
    {
        e:"alphanumeric", 
        i:"alfanumerico"
    },
    {
        e:"alpine", 
        i:"alpino"
    },
    {
        e:"already", 
        i:"già"
    },
    {
        e:"also", 
        i:"anche"
    },
    {
        e:"altar", 
        i:"altare"
    },
    {
        e:"(to) alter", 
        i:"alterare"
    },
    {
        e:"alteration", 
        i:"alterazione"
    },
    {
        e:"altercation", 
        i:"alterco"
    },
    {
        e:"alternate", 
        i:"alternato"
    },
    {
        e:"(to) alternate", 
        i:"alternare"
    },
    {
        e:"alternative", 
        i:"alternativo"
    },
    {
        e:"alternator", 
        i:"alternatore"
    },
    {
        e:"although", 
        i:"sebbene"
    },
    {
        e:"altimeter", 
        i:"altimetro"
    },
    {
        e:"altitude", 
        i:"altitudine"
    },
    {
        e:"altogether", 
        i:"completamente"
    },
    {
        e:"altruism", 
        i:"altruismo"
    },
    {
        e:"altruist", 
        i:"altruista"
    },
    {
        e:"altruistic", 
        i:"altruistico"
    },
    {
        e:"alum", 
        i:"allume"
    },
    {
        e:"aluminum", 
        i:"alluminio"
    },
    {
        e:"alveolary", 
        i:"alveolare"
    },
    {
        e:"alveolus",
        i:"alveolo"
    },
    {
        e:"always", 
        i:"sempre"
    },
    {
        e:"amalgam", 
        i:"amalgama"
    },
    {
        e:"(to) amalgamate", 
        i:"amalgamare"
    },
    {
        e:"amalgamation", 
        i:"amalgamazione"
    },
    {
        e:"amanuensis", 
        i:"amanuense"
    },
    {
        e:"amarant", 
        i:"amaranto"
    },
    {
        e:"amaryllis", 
        i:"amarilli"
    },
    {
        e:"(to) amass", 
        i:"ammassare"
    },
    {
        e:"amateur", 
        i:"dilettante"
    },
    {
        e:"amateurish", 
        i:"dilettantesco"
    },
    {
        e:"amatory", 
        i:"amatorio"
    },
    {
        e:"(to) amaze", 
        i:"stupire"
    },
    {
        e:"amazed", 
        i:"stupito"
    },
    {
        e:"amazement", 
        i:"stupore"
    },
    {
        e:"amazing", 
        i:"sorprendente"
    },
    {
        e:"amazon", 
        i:"amazzone"
    },
    {
        e:"ambassador", 
        i:"ambasciatore"
    },
    {
        e:"ambassadorial", 
        i:"da ambasciatore"
    },
    {
        e:"amber", 
        i:"ambra"
    },
    {
        e:"ambidextrous", 
        i:"ambidestro"
    },
    {
        e:"ambience", 
        i:"ambiente"
    },
    {
        e:"ambient", 
        i:"ambiente"
    },
    {
        e:"ambiguity", 
        i:"ambiguità"
    },
    {
        e:"ambiguous", 
        i:"ambiguo"
    },
    {
        e:"ambit", 
        i:"ambito"
    },
    {
        e:"ambition", 
        i:"ambizione"
    },
    {
        e:"ambitious", 
        i:"ambizioso"
    },
    {
        e:"ambivalence", 
        i:"indecisione"
    },
    {
        e:"ambivalent", 
        i:"indeciso"
    },
    {
        e:"amble", 
        i:"ambio"
    },
    {
        e:"ambulance", 
        i:"ambulanza"
    },
    {
        e:"ambush", 
        i:"imboscata"
    },
    {
        e:"ameba", 
        i:"ameba"
    },
    {
        e:"(to) ameliorate", 
        i:"migliorare"
    },
    {
        e:"amelioration", 
        i:"miglioramento"
    },
    {
        e:"(to) amend", 
        i:"emendare"
    },
    {
        e:"amendment", 
        i:"emendamento"
    },
    {
        e:"amends", 
        i:"fare ammenda"
    },
    {
        e:"amenity", 
        i:"comodità"
    },
    {
        e:"amethyst", 
        i:"ametista"
    },
    {
        e:"amiability", 
        i:"amabilità"
    },
    {
        e:"amiable", 
        i:"amabile"
    },
    {
        e:"amid", 
        i:"tra"
    },
    {
        e:"amino acid", 
        i:"amminoacido"
    },
    {
        e:"amity", 
        i:"amicizia"
    },
    {
        e:"ammeter", 
        i:"amperometro"
    },
    {
        e:"ammo", 
        i:"munizioni"
    },
    {
        e:"ammonia", 
        i:"ammoniaca"
    },
    {
        e:"ammunition", 
        i:"munizione"
    },
    {
        e:"amnesia", 
        i:"amnesia"
    },
    {
        e:"amnesty", 
        i:"amnistia"
    },
    {
        e:"aminocentesis", 
        i:"amniocentesi"
    },
    {
        e:"amniotic", 
        i:"amniotico"
    },
    {
        e:"among", 
        i:"tra"
    },
    {
        e:"amoral", 
        i:"amorale"
    },
    {
        e:"amorous", 
        i:"passionale"
    },
    {
        e:"amorphous", 
        i:"amorfo"
    },
    {
        e:"amortization", 
        i:"ammortamento"
    },
    {
        e:"(to) amortize", 
        i:"ammortizzare"
    },
    {
        e:"amount", 
        i:"totale"
    },
    {
        e:"(to) amount", 
        i:"ammontare"
    },
    {
        e:"amour", 
        i:"tresca"
    },
    {
        e:"amperage", 
        i:"amperaggio"
    },
    {
        e:"ampere", 
        i:"ampere"
    },
    {
        e:"amphetamine", 
        i:"anfetamina"
    },

]