const Dizionario  = [
    {
        e:"an",
        i:"un"
    }, 
    {
        e:"abacus",
        i:"abaco"
    }, 
    {
        e:"abandon", 
        i:"abbandono"
    },
    {
        e:"abandoned",
        i:"abbandonato"
    }, 
    {
        e:"(to) abase", 
        i:"abbandonare"
    }, 
    {
        e:"abasement", 
        i:"umiliazione"
    },
    {
        e:"(to) abash", 
        i:"confondere"
    }, 
    {
        e:"abashment", 
        i:"confusione"
    },
    {
        e:"(to) abate", 
        i:"ridurre"
    },
    {
        e:"abatement", 
        i:"riduzione"
    },
    {
        e:"abattoir", 
        i:"mattatoio"
    },
    {
        e:"abbess", 
        i:"badessa"
    },
    {
        e:"abbey", 
        i:"abbazia"
    },
    {
        e:"abbot", 
        i:"abate"
    },
    {
        e:"abbreviate", 
        i:"abbreviare"
    },
    {
        e:"abbreviation", 
        i:"abbreviazione"
    },
    {
        e:"abdication", 
        i:"abdicazione"
    },
    {
        e:"abdomen", 
        i:"addome"
    },
    {
        e:"abdominal", 
        i:"addominale"
    },
    {
        e:"(to) abduct", 
        i:"rapire"
    },
    {
        e:"abduction", 
        i:"rapimento"
    },
    {
        e:"aberrance", 
        i:"aberrazione"
    },
    {
        e:"aberrant", 
        i:"aberrante"
    },
    {
        e:"aberration", 
        i:"aberrazione"
    },
    {
        e:"(to) abet", 
        i:"favoreggiare"
    },
    {
        e:"abetment", 
        i:"favoreggiamento"
    },
    {
        e:"abetter", 
        i:"favoreggiatore"
    },
    {
        e:"abeyance", 
        i:"sospensione"
    },
    {
        e:"abhor", 
        i:"aborrire"
    },
    {
        e:"abhorrence", 
        i:"ripugnanza"
    },
    {
        e:"abhorrent", 
        i:"ripugnante"
    },
    {
        e:"(to) abide", 
        i:"tollerare"
    },
    {
        e:"abiding (agg)", 
        i:"costante"
    },
    {
        e:"ability", 
        i:"abilità"
    },
    {
        e:"abject", 
        i:"abietto"
    },
    {
        e:"abjuration", 
        i:"abiura"
    },
    {
        e:"abjure", 
        i:"abiurare"
    },
    {
        e:"ablaze", 
        i:"in fiamme"
    },
    {
        e:"able", 
        i:"capace"
    },
    {
        e:"ablution", 
        i:"abluzione"
    },
    {
        e:"ably", 
        i:"abilmente"
    },
    {
        e:"abnegate", 
        i:"rinunciare"
    },
    {
        e:"abnegation", 
        i:"abnegazione"
    },
    {
        e:"abnormal", 
        i:"anormale"
    },
    {
        e:"abnormality", 
        i:"anormalità"
    },
    {
        e:"abnormally", 
        i:"eccezionalmente"
    },
    {
        e:"aboard", 
        i:"a bordo"
    },
    {
        e:"abode", 
        i:"residenza"
    },
    {
        e:"(to) abolish", 
        i:"abolire"
    },
    {
        e:"abolition", 
        i:"abolizione"
    },
    {
        e:"abolitionist", 
        i:"abolizionista"
    },
    {
        e:"abominable", 
        i:"abominevole"
    },
    {
        e:"(to) abominate", 
        i:"aberrare"
    },
    {
        e:"abomination", 
        i:"odio"
    },
    {
        e:"aboriginal", 
        i:"aborigeno"
    },
    {
        e:"aborigine", 
        i:"aborigeno"
    },
    {
        e:"(to) abort", 
        i:"interrompere"
    },
    {
        e:"abortion", 
        i:"aborto"
    },
    {
        e:"abortive", 
        i:"abortivo"
    },
    {
        e:"(to) abound", 
        i:"abbondare"
    },
    {
        e:"about", 
        i:"circa"
    },
    {
        e:"above", 
        i:"oltre"
    },
    {
        e:"abrasion", 
        i:"abrasione"
    },
    {
        e:"abrasive", 
        i:"abrasivo"
    },
    {
        e:"(to) abridge", 
        i:"accorciare"
    },
    {
        e:"abridgement", 
        i:"riduzione"
    },
    {
        e:"abroad", 
        i:"all'estero"
    },
    {
        e:"abrogate", 
        i:"abrogare"
    },
    {
        e:"abrogation", 
        i:"abrogazione"
    },
    {
        e:"abrupt", 
        i:"inaspettato"
    },
    {
        e:"abscess", 
        i:"ascesso"
    },
    {
        e:"abscissa", 
        i:"ascissa"
    },
    {
        e:"(to) abscond", 
        i:"fuggire"
    },
    {
        e:"absence", 
        i:"assenza"
    },
    {
        e:"absent", 
        i:"assente"
    },
    {
        e:"absentely", 
        i:"distrattamente"
    },
    {
        e:"absolute", 
        i:"assoluto"
    },
    {
        e:"absolutness", 
        i:"assolutezza"
    },
    {
        e:"absolution", 
        i:"assoluzione"
    },
    {
        e:"absolutism", 
        i:"assolutismo"
    },
    {
        e:"absolutist", 
        i:"assolutista"
    },
    {
        e:"(to) absolve", 
        i:"assolvere"
    },
    {
        e:"(to) absorb", 
        i:"assorbire"
    },
    {
        e:"absorbed", 
        i:"assorbito"
    },
    {
        e:"absorbent", 
        i:"assorbente"
    },
    {
        e:"absorbing (agg)", 
        i:"avvincente"
    },
    {
        e:"absorption", 
        i:"assorbimento"
    },
    {
        e:"(to) abstain", 
        i:"astenersi"
    },
    {
        e:"abstainer", 
        i:"astenuto"
    },
    {
        e:"abstemious", 
        i:"sobrio"
    },
    {
        e:"abstemiousness", 
        i:"sobrietà"
    },
    {
        e:"abstention", 
        i:"astensione"
    },
    {
        e:"abstinence", 
        i:"astinenza"
    },
    {
        e:"abstinent", 
        i:"astinente"
    },
    {
        e:"abstract", 
        i:"astratto"
    },
    {
        e:"(to) abstract", 
        i:"sottrarre"
    },
    {
        e:"abstracted", 
        i:"distratto"
    },
    {
        e:"abstraction", 
        i:"astrazione"
    },
    {
        e:"abstractionism", 
        i:"astrattismo"
    },
    {
        e:"abstractionist", 
        i:"astrattista"
    },
    {
        e:"abstruse", 
        i:"astruso"
    },
    {
        e:"absurd", 
        i:"assurdo"
    },
    {
        e:"absurdity", 
        i:"assurdità"
    },
    {
        e:"abulia", 
        i:"abulia"
    },
    {
        e:"abundance", 
        i:"abbondanza"
    },
    {
        e:"abundant", 
        i:"abbondante"
    },
    {
        e:"(to) abuse", 
        i:"approfittare"
    },
    {
        e:"abusive", 
        i:"abusivo"
    },
    {
        e:"(to) about (to something)", 
        i:"confinare"
    },
    {
        e:"abutment", 
        i:"appoggio"
    },
    {
        e:"abysmal", 
        i:"terribile"
    },
    {
        e:"abyss", 
        i:"abisso"
    },
    {
        e:"abyssinian", 
        i:"abissino"
    },
    {
        e:"acacia", 
        i:"acacia"
    },
    {
        e:"academic", 
        i:"accademico"
    },
    {
        e:"academician (person)", 
        i:"accademico"
    },
    {
        e:"academy", 
        i:"accademia"
    },
    {
        e:"acanthus", 
        i:"acanto"
    },
    {
        e:"(to) accede", 
        i:"accedere"
    },
    {
        e:"(to) accelerate", 
        i:"accelerare"
    },
    {
        e:"acceleration", 
        i:"accelerazione"
    },
    {
        e:"accelerator", 
        i:"acceleratore"
    },
    {
        e:"accent", 
        i:"accento"
    },
    {
        e:"(to) accent", 
        i:"accentare"
    },
    {
        e:"(to) accentuate", 
        i:"accentuare"
    },
    {
        e:"accentuation", 
        i:"accentuazione"
    },
    {
        e:"(to) accept", 
        i:"accettare"
    },
    {
        e:"acceptable", 
        i:"accettabile"
    },
    {
        e:"acceptance", 
        i:"accettazione"
    },
    {
        e:"accepter", 
        i:"accettante"
    },
    {
        e:"acceptor", 
        i:"accettante"
    },
    {
        e:"access", 
        i:"accesso"
    },
    {
        e:"(to) access", 
        i:"accedere"
    },
    {
        e:"accessary", 
        i:"complice"
    },
    {
        e:"accessible", 
        i:"accessibile"
    },
    {
        e:"accession", 
        i:"ascesa"
    },
    {
        e:"accessorial (agg)", 
        i:"accessorio"
    },
    {
        e:"accessory", 
        i:"accessorio"
    },
    {
        e:"access road", 
        i:"strada secondaria"
    },
    {
        e:"accidence", 
        i:"morfologia"
    },
    {
        e:"accident", 
        i:"incidente"
    },
    {
        e:"accidental", 
        i:"accidentale"
    },
    {
        e:"acclaim", 
        i:"consenso"
    },
    {
        e:"(to) acclaim", 
        i:"acclamare"
    },
    {
        e:"acclamation", 
        i:"acclamazione"
    },
    {
        e:"acclimate", 
        i:"acclimatizzarsi"
    },
    {
        e:"acclimatization", 
        i:"acclimatizzarsi"
    },
    {
        e:"(to) acclimatize", 
        i:"acclimatizzarsi"
    },  
    {
        e:"accolade", 
        i:"lode"
    },   
    {
        e:"(to) accomodate", 
        i:"accomodare"
    },
    {
        e:"accomodating (agg)", 
        i:"servizievole"
    },
    {
        e:"accomodation", 
        i:"alloggio"
    },
    {
        e:"accompaniment", 
        i:"accompagnamento"
    },
    {
        e:"accompanist", 
        i:"accompagnatore"
    },
    {
        e:"(to) accompany", 
        i:"accompagnare"
    },
    {
        e:"accomplice", 
        i:"complice"
    },
    {
        e:"(to) accomplish", 
        i:"compiere"
    },
    {
        e:"accomplished", 
        i:"finito"
    },
    {
        e:"accomplishment", 
        i:"compimento"
    },
    {
        e:"accord", 
        i:"accordo"
    },
    {
        e:"(to) accord", 
        i:"accordare"
    },
    {
        e:"accordance", 
        i:"accordo"
    },
    {
        e:"accordingly", 
        i:"quindi"
    },
    {
        e:"according to", 
        i:"secondo"
    },
    {
        e:"accordion", 
        i:"fisarmonica"
    },
    {
        e:"(to) acost", 
        i:"avvicinare"
    },
    {
        e:"account", 
        i:"conto"
    },
    {
        e:"(to) account", 
        i:"stimare"
    },
    {
        e:"accountable", 
        i:"responsabile"
    },
    {
        e:"accountancy", 
        i:"contabilità"
    },
    {
        e:"accountant", 
        i:"contabile"
    },
    {
        e:"accounting", 
        i:"contabilita"
    },
    {
        e:"(to) accredit", 
        i:"accreditare"
    },
    {
        e:"accretion", 
        i:"accrescimento"
    },
    {
        e:"(to) acrue", 
        i:"maturare"
    },
    {
        e:"(to) accumulate", 
        i:"accumulare"
    },
    {
        e:"accumuluation", 
        i:"accumulazione"
    },
    {
        e:"accumulative", 
        i:"accumulativo"
    },
    {
        e:"accumulator", 
        i:"accumulatore"
    },
    {
        e:"accuracy", 
        i:"precisione"
    },
    {
        e:"accurate", 
        i:"preciso"
    },
    {
        e:"accursed", 
        i:"maledetto"
    },
    {
        e:"accusable", 
        i:"accusabile"
    },
    {
        e:"accusation", 
        i:"accusa"
    },
    {
        e:"(to) accuse", 
        i:"accusare"
    },
    {
        e:"accused", 
        i:"accusato"
    },
    {
        e:"accuser", 
        i:"accusatore"
    },
    {
        e:"(to) accustom", 
        i:"abituare"
    },  
    {
        e:"accustomed", 
        i:"abituato"
    },
    {
        e:"ace", 
        i:"asso"
    },
    {
        e:"acerbity", 
        i:"acerbità"
    },
    {
        e:"acetate", 
        i:"acetato"
    },
    {
        e:"acetic", 
        i:"acetico"
    },
    {
        e:"(to) acetify", 
        i:"acetificare"
    },
    {
        e:"acetone", 
        i:"acetone"
    },
    {
        e:"acetylene", 
        i:"acetilene"
    },
    {
        e:"ache", 
        i:"dolore"
    },
    {
        e:"(to) ache", 
        i:"dolere"
    },
    {
        e:"(to) achieve", 
        i:"ottenere"
    },
    {
        e:"achievement", 
        i:"obiettivo"
    },
    {
        e:"achromatic", 
        i:"acromatico"
    },
    {
        e:"acid", 
        i:"acido"
    },
    {
        e:"(to) acidify", 
        i:"acidificare"
    },
    {
        e:"acidity", 
        i:"acidità"
    },
    {
        e:"(to) acknowledge", 
        i:"riconoscere"
    },  
    {
        e:"acknowledgement", 
        i:"riconoscimento"
    },
    {
        e:"acme", 
        i:"acme"
    },
    {
        e:"acne", 
        i:"acne"
    },
    {
        e:"acolyte", 
        i:"accolito"
    },
    {
        e:"acorn", 
        i:"ghianda"
    },
    {
        e:"acoustic", 
        i:"acustico"
    },
    {
        e:"acoustics", 
        i:"acustica"
    },
    {
        e:"(to) acquaint", 
        i:"informare"
    },
    {
        e:"acquaintance", 
        i:"conoscenza"
    },
    {
        e:"(to) acquiesce", 
        i:"acconsentire"
    },
    {
        e:"acquiescence", 
        i:"arrendevolezza"
    },
    {
        e:"acquiescent", 
        i:"arrendevole"
    },
    {
        e:"(to) acquire", 
        i:"acquisire"
    },
    {
        e:"acquisition", 
        i:"acquisizione"
    },
    {
        e:"acquisitive", 
        i:"avido"
    },
    {
        e:"(to) acquit", 
        i:"assolvere"
    },
    {
        e:"acquittal", 
        i:"assoluzione"
    },
    {
        e:"acre", 
        i:"acro"
    },
    {
        e:"acrid", 
        i:"aspro"
    },
    {
        e:"acrimonious", 
        i:"astioso"
    },
    {
        e:"acrimony", 
        i:"astiosità"
    },
    {
        e:"acrobat", 
        i:"acrobata"
    },
    {
        e:"acrobatic", 
        i:"acrobatico"
    },
    {
        e:"acrobatics", 
        i:"acrobazia"
    },
    {
        e:"acronym", 
        i:"acronimo"
    },
    {
        e:"across", 
        i:"attraverso"
    },
    {
        e:"acrostic", 
        i:"acrostico"
    },
    {
        e:"acrylic", 
        i:"acrilico"
    },
    {
        e:"act", 
        i:"azione"
    },
    {
        e:"(to) act", 
        i:"agire"
    },
    {
        e:"acting", 
        i:"recitazione"
    },
    {
        e:"action", 
        i:"azione"
    },
    {
        e:"actionable", 
        i:"azionabile"
    },
    {
        e:"(to) activate", 
        i:"attivare"
    },
    {
        e:"active", 
        i:"attivo"
    },
    {
        e:"activist", 
        i:"attivista"
    },
    {
        e:"activity", 
        i:"attività"
    },
    {
        e:"actor", 
        i:"attore"
    },
    {
        e:"actress", 
        i:"attrice"
    },
    {
        e:"actual", 
        i:"attuale"
    },
    {
        e:"actually", 
        i:"veramente"
    },
    {
        e:"actuary", 
        i:"attuario"
    },
    {
        e:"(to) actuate", 
        i:"attuare"
    },
    {
        e:"acuity", 
        i:"acutezza"
    },
    {
        e:"acumen", 
        i:"acume"
    },
    {
        e:"acupuncture", 
        i:"agopuntura"
    },
    {
        e:"acupuncturist", 
        i:"agopunturista"
    },
    {
        e:"acute", 
        i:"acuto"
    },
    {
        e:"ad", 
        i:"pubblicità"
    },
    {
        e:"adage", 
        i:"adagio"
    },
    {
        e:"adam", 
        i:"adamo"
    },
    {
        e:"adamant", 
        i:"risoluto"
    },
    {
        e:"(to) adapt", 
        i:"adattare"
    },
    {
        e:"adaptibility", 
        i:"adattabilità"
    },
    {
        e:"adaptable", 
        i:"adattabile"
    },
    {
        e:"adaptation", 
        i:"adattamento"
    },
    {
        e:"adapter", 
        i:"adattatore"
    },
    {
        e:"(to) add", 
        i:"aggiungere"
    },
    {
        e:"addendum", 
        i:"addendo"
    },
    {
        e:"adder", 
        i:"vipera"
    },
    {
        e:"addicted", 
        i:"dipendente"
    },
    {
        e:"addiction", 
        i:"dipendenza"
    },
    {
        e:"addictive", 
        i:"provoca dipendenza"
    },
    {
        e:"addition", 
        i:"addizione"
    },
    {
        e:"additional", 
        i:"supplementare"
    },
    {
        e:"additionally", 
        i:"inoltre"
    },
    {
        e:"additive", 
        i:"additivo"
    },
    {
        e:"(to) addle", 
        i:"confondere"
    },
    {
        e:"addled", 
        i:"marcio"
    },
    {
        e:"address", 
        i:"indirizzo"
    },
    {
        e:"(to) address", 
        i:"indirizzare"
    },
    {
        e:"addressee", 
        i:"destinatario"
    },
    {
        e:"(to) aduce", 
        i:"addurre"
    },
    {
        e:"adenoids", 
        i:"adenoidi"
    },
    {
        e:"adenoma", 
        i:"adenoma"
    },
    {
        e:"adept", 
        i:"esperto"
    },
    {
        e:"adequacy", 
        i:"adeguatezza"
    },
    {
        e:"adequate", 
        i:"adeguato"
    },
    {
        e:"(to) adhere", 
        i:"aderire"
    },
    {
        e:"adherence", 
        i:"aderenza"
    },
    {
        e:"adherent", 
        i:"aderente"
    },
    {
        e:"adhesion", 
        i:"adesione"
    },
    {
        e:"adhesive", 
        i:"adesivo"
    },
    {
        e:"adipose", 
        i:"adiposo"
    },
    {
        e:"adjacent", 
        i:"adiacente"
    },
    {
        e:"adjective", 
        i:"aggettivo"
    },
    {
        e:"(to) adjoin", 
        i:"confinare"
    },
    {
        e:"adjoining", 
        i:"adiacente"
    },
    {
        e:"(to) adjourn", 
        i:"aggiornare"
    },
    {
        e:"adjournment", 
        i:"aggiornamento"
    },
    {
        e:"(to) adjudge", 
        i:"giudicare"
    },
    {
        e:"(to) adjudicate", 
        i:"aggiudicare"
    },
    {
        e:"adjudicator", 
        i:"arbitro"
    },
    {
        e:"adjunct", 
        i:"accessorio"
    },
    {
        e:"(to) adjust", 
        i:"aggiustare"
    },
    {
        e:"adjustable", 
        i:"aggiustabile"
    },
    {
        e:"adjustment", 
        i:"aggiustamento"
    },
    {
        e:"adjutant", 
        i:"aiutante"
    },
    {
        e:"(to) ad-lib", 
        i:"improvvisare"
    },
    {
        e:"adman", 
        i:"pubblicitario"
    },
    {
        e:"admin", 
        i:"amministratore"
    },
    {
        e:"(to) administer", 
        i:"amministrare"
    },
    {
        e:"administration", 
        i:"amministrazione"
    },
    {
        e:"administrative", 
        i:"amministrativo"
    },
    {
        e:"administrator", 
        i:"amministratore"
    },
    {
        e:"admirable", 
        i:"ammirabile"
    },
    {
        e:"admiral", 
        i:"ammiraglio"
    },
    {
        e:"admiration", 
        i:"ammirazione"
    },
    {
        e:"(to) admire", 
        i:"ammirare"
    },
    {
        e:"admirer", 
        i:"ammiratore"
    },
    {
        e:"admiring (agg)", 
        i:"ammirato"
    },
    {
        e:"admissible", 
        i:"ammissibile"
    },
    {
        e:"admission", 
        i:"ammissione"
    },
    {
        e:"(to) admit", 
        i:"ammettere"
    },
    {
        e:"admittedly", 
        i:"dichiaratamente"
    },
    {
        e:"admixture", 
        i:"additivo"
    },
    {
        e:"(to) admonish", 
        i:"ammonire"
    },
    {
        e:"admonition", 
        i:"ammonizione"
    },
    {
        e:"ado", 
        i:"confusione"
    },
    {
        e:"adolescence", 
        i:"adolescenza"
    },
    {
        e:"adolescent", 
        i:"adolescente"
    },
    {
        e:"(to) adopt", 
        i:"adottare"
    },
    {
        e:"adoption", 
        i:"adozione"
    },
    {
        e:"adoptive", 
        i:"adottivo"
    },
    {
        e:"adorable", 
        i:"adorabile"
    },
    {
        e:"adoration", 
        i:"adorazione"
    },
    {
        e:"(to) adore", 
        i:"adorare"
    },
    {
        e:"(to) adorn", 
        i:"adornare"
    },
    {
        e:"adornment", 
        i:"ornamento"
    },
    {
        e:"adrenaline", 
        i:"adrenalina"
    },
    {
        e:"adriatic", 
        i:"adriatico"
    },
    {
        e:"adrift", 
        i:"deriva"
    },
    {
        e:"adulation", 
        i:"adulazione"
    },
    {
        e:"adult", 
        i:"adulto"
    },
    {
        e:"(to) adulterate", 
        i:"adulterare"
    },
    {
        e:"adulteration", 
        i:"adulterazione"
    },
    {
        e:"adulterer", 
        i:"adultero"
    },
    {
        e:"adulteress", 
        i:"adultera"
    },
    {
        e:"adulterous", 
        i:"adultero"
    },
    {
        e:"adultery", 
        i:"adulterio"
    },
    {
        e:"adulthood", 
        i:"età adulta"
    },
    {
        e:"adumbrate", 
        i:"adombrare"
    },
    {
        e:"advance", 
        i:"avanzamento"
    },
    {
        e:"(to) advance", 
        i:"avanzare"
    },
    {
        e:"advanced", 
        i:"avanzato"
    },
    {
        e:"advancement", 
        i:"avanzamento"
    },
    {
        e:"advantage", 
        i:"vantaggio"
    },
    {
        e:"(to) advantage", 
        i:"avvantaggiare"
    },
    {
        e:"advantageous", 
        i:"vantaggioso"
    },
    {
        e:"advent", 
        i:"avvento"
    },
    {
        e:"adventitous", 
        i:"casuale"
    },
    {
        e:"adventure", 
        i:"avventura"
    },
    {
        e:"adventurer", 
        i:"avventuriero"
    },
    {
        e:"adventuress", 
        i:"avventuriera"
    },
    {
        e:"adventurous", 
        i:"avventuroso"
    },
    {
        e:"adverb", 
        i:"avverbio"
    },
    {
        e:"adverbial", 
        i:"avverbiale"
    },
    {
        e:"asversarial", 
        i:"rivale"
    },
    {
        e:"adversary", 
        i:"avversario"
    },
    {
        e:"adverse", 
        i:"contrario"
    },
    {
        e:"adversely", 
        i:"negativamente"
    },
    {
        e:"adversity", 
        i:"avversità"
    },
    {
        e:"advert", 
        i:"pubblicità"
    },
    {
        e:"(to) advertize", 
        i:"pubblicizzare"
    },
    {
        e:"advertisement", 
        i:"pubblicità"
    },
    {
        e:"advertiser", 
        i:"inserzionista"
    },
    {
        e:"advertising (agg)", 
        i:"pubblicità"
    },
    {
        e:"advice", 
        i:"consiglio"
    },
    {
        e:"advisability", 
        i:"opportunità"
    },
    {
        e:"advisable", 
        i:"consigliabile"
    },
    {
        e:"(to) advise", 
        i:"consigliare"
    },
    {
        e:"advisedly", 
        i:"volutamente"
    },
    {
        e:"adviser", 
        i:"consigliere"
    },
    {
        e:"advocacy", 
        i:"difesa"
    },
    {
        e:"advocate", 
        i:"difensore"
    },
    {
        e:"(to) advocate", 
        i:"difendere"
    },
    {
        e:"aeon", 
        i:"eternità"
    },
    {
        e:"(to) aerate", 
        i:"aerare"
    },
    {
        e:"aeration", 
        i:"aerazione"
    },
    {
        e:"aerial", 
        i:"aereo"
    },
    {
        e:"aeriform", 
        i:"aeriforme"
    },
    {
        e:"aerobatics", 
        i:"acrobatica aerea"
    },
    {
        e:"aerobics", 
        i:"aerobica"
    },
    {
        e:"aerodynamic", 
        i:"aerodinamico"
    },
    {
        e:"aerodynamics", 
        i:"aerodinamica"
    },
    {
        e:"aerofoil", 
        i:"alettone"
    },
    {
        e:"aerograph", 
        i:"aerografo"
    },
    {
        e:"aerometer", 
        i:"aerometro"
    },
    {
        e:"aeronautical", 
        i:"aeronautico"
    },
    {
        e:"aeronautics", 
        i:"aeronautica"
    },
    {
        e:"aerophone", 
        i:"aerofono"
    },
    {
        e:"aeroplane", 
        i:"aeroplano"
    },
    {
        e:"aerosol", 
        i:"aerosol"
    },
    {
        e:"aerospace", 
        i:"aerospaziale"
    },
    {
        e:"aesthete", 
        i:"esteta"
    },
    {
        e:"aesthetic", 
        i:"estetico"
    },
    {
        e:"aestheticism", 
        i:"estetismo"
    },
    {
        e:"afar", 
        i:"lontano"
    },
    {
        e:"affability", 
        i:"cortesia"
    },
    {
        e:"affable", 
        i:"cortese"
    },
    {
        e:"affair", 
        i:"affare"
    },
    {
        e:"(to) affect", 
        i:"influenzare"
    },
    {
        e:"affectiation", 
        i:"affettazione"
    },
    {
        e:"affected", 
        i:"affettato"
    },
    {
        e:"affection", 
        i:"affetto"
    },
    {
        e:"affectionate", 
        i:"affettuoso"
    },
    {
        e:"affiliate", 
        i:"affiliato"
    },
    {
        e:"affiliation", 
        i:"affiliazione"
    },
    {
        e:"affinity", 
        i:"affinità"
    },
    {
        e:"(to) affirm", 
        i:"affermare"
    },
    {
        e:"affirmation", 
        i:"affermazione"
    },
    {
        e:"affirmative", 
        i:"affermativo"
    },
    {
        e:"affix", 
        i:"affisso"
    },
    {
        e:"(to) affix", 
        i:"affiggere"
    },
    {
        e:"(to) afflict", 
        i:"affliggere"
    },
    {
        e:"affliction", 
        i:"afflizione"
    },
    {
        e:"affluence", 
        i:"ricchezza"
    },
    {
        e:"affluent", 
        i:"ricco"
    },
    {
        e:"afflux", 
        i:"afflusso"
    },
    {
        e:"(to) afford", 
        i:"permettere"
    },
    {
        e:"(to) afforest", 
        i:"imboschire"
    },
    {
        e:"afforestation", 
        i:"imboschimento"
    },
    {
        e:"affray", 
        i:"rissa"
    },
    {
        e:"affront", 
        i:"affronto"
    },
    {
        e:"(to) affront", 
        i:"insultare"
    },
    {
        e:"afire", 
        i:"in fiamme"
    },
    {
        e:"aflame", 
        i:"in fiamme"
    },
    {
        e:"afloat", 
        i:"a galla"
    },
    {
        e:"afoot", 
        i:"in corso"
    },
    {
        e:"afraid", 
        i:"spaventato"
    },
    {
        e:"afresh", 
        i:"da capo"
    },
    {
        e:"aft", 
        i:"a poppa"
    },
    {
        e:"after", 
        i:"dopo"
    },
    {
        e:"afterglow", 
        i:"tramonto"
    },
    {
        e:"afterlife", 
        i:"aldilà"
    },
    {
        e:"afternoon", 
        i:"pomeriggio"
    },
    {
        e:"afters", 
        i:"dessert"
    },
    {
        e:"aftershave", 
        i:"dopobarba"
    },
    {
        e:"aftertaste", 
        i:"retrogusto"
    },
    {
        e:"afterthought", 
        i:"ripensamento"
    },
    {
        e:"afterward", 
        i:"poi"
    },
    {
        e:"again", 
        i:"di nuovo"
    },
    {
        e:"against", 
        i:"contro"
    },
    {
        e:"agape", 
        i:"stupito"
    },
    {
        e:"agate", 
        i:"agata"
    },
    {
        e:"age", 
        i:"età"
    },
    {
        e:"(to) age", 
        i:"invecchiare"
    },
    {
        e:"aged", 
        i:"vecchio"
    },
    {
        e:"ageing", 
        i:"invecchiamento"
    },





































]